name: "AI PR Summary"

on:
  pull_request_target:
    types: [opened, synchronize]

  push:
    branches:
      - main

jobs:
  generate-summary:
    if: github.event_name == 'push' | 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate PR Summary
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/generate_summary.py "${{ github.event.pull_request.title }}" "${{ github.event.pull_request.diff_url }}" "${{ github.event.pull_request.number }}"

  update-changelog:
    if: github.event_name == 'push' | 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update changelog
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/update_changelog.py
